site_name: "Juniper Terraform SRX"
site_description: "Build and deploy Juniper SRX configurations with Terraform."
site_url: "https://cdot65.github.io/juniper-terraform-srx/"
repo_name: "cdot65/juniper-terraform-srx"
repo_url: "https://github.com/cdot65/juniper-terraform-srx"
edit_uri: "edit/mainline/site/content"
copyright: "Copyright &copy; 2022 cdot65"
docs_dir: "site/content"
site_dir: "docs"
extra_css:
  - "stylesheets/cdot65.css"

nav:
  - Home: "index.md"
  - Documentation:
      - Overview: "docs/overview.md"
      - Ansible:
          - Modules:
              - blueprint: "docs/ansible/modules/blueprint.md"
              - design: "docs/ansible/modules/design.md"
              - resources: "docs/ansible/modules/resources.md"
          - Plugins: "docs/network/overview.md"
          - Roles: "docs/network/overview.md"
          - Templates: "docs/network/overview.md"
      - Network:
          - Overview: "docs/network/overview.md"
      - Lab Environment:
          - Overview: "docs/network/overview.md"

theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "assets/images/favicon.png"
  language: "en"
  features:
    - "tabs"
    - "instant"

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - "search"
  - macros:
      include_dir: "site/content/docs/include"
